/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Settings Page */
        get: operations["settings_page_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inverters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inverters Page */
        get: operations["inverters_page_inverters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plans Page */
        get: operations["plans_page_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Billing Page */
        get: operations["billing_page_billing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api State */
        get: operations["api_state_api_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Chart */
        get: operations["api_chart_api_chart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Bill */
        get: operations["api_bill_api_bill_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/close-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Close Day */
        post: operations["api_close_day_api_close_day_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}/tou": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Tou Read */
        get: operations["api_tou_read_api_plans__plan_id__tou_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Settings */
        post: operations["api_settings_api_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inverters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Inverters */
        post: operations["api_inverters_api_inverters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Plans */
        post: operations["api_plans_api_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tou/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Tou */
        post: operations["api_tou_api_tou__plan_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/poll-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Poll Now */
        post: operations["api_poll_now_api_poll_now_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Ai Recommend */
        post: operations["api_ai_recommend_api_ai_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Ai Apply */
        post: operations["api_ai_apply_api_ai_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AppSettings
         * @description Application-wide preferences.
         */
        AppSettings: {
            /**
             * Theme
             * @default classic-dark
             * @enum {string}
             */
            theme: "classic-light" | "classic-dark" | "deep-ocean" | "ember-core";
            /**
             * Mode
             * @default manual
             * @enum {string}
             */
            mode: "manual" | "ai";
            /**
             * Poll Interval Seconds
             * @default 30
             */
            poll_interval_seconds: number;
            /**
             * Site Name
             * @default Solarmax
             */
            site_name: string;
            /**
             * Site Lat
             * @default -27.4698
             */
            site_lat: number;
            /**
             * Site Lon
             * @default 153.0251
             */
            site_lon: number;
            /**
             * Site Timezone
             * @default Australia/Brisbane
             */
            site_timezone: string;
            /** Active Plan Id */
            active_plan_id?: number | null;
        };
        /** BillSummaryResponse */
        BillSummaryResponse: {
            plan: components["schemas"]["PowerPlanResponse"] | null;
            /** Total Cents */
            total_cents: number;
            /** Rows */
            rows?: components["schemas"]["BillingLine"][];
            /** Daily */
            daily?: components["schemas"]["BillingLine"][];
            /** Today Grid Import Kwh */
            today_grid_import_kwh: number;
            /** Today Grid Export Kwh */
            today_grid_export_kwh: number;
            /** Supply Charge Cents */
            supply_charge_cents: number;
            /** Supply Charge Days */
            supply_charge_days: number;
            /** Billing Window Applied */
            billing_window_applied: boolean;
            /**
             * Lines
             * @deprecated
             */
            lines?: unknown[];
            /**
             * Rollups
             * @deprecated
             */
            rollups?: unknown[];
        };
        /**
         * BillingLine
         * @description Display-friendly billing breakdown entry.
         */
        BillingLine: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Period Label */
            period_label: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "import" | "export" | "fixed";
            /** Kwh */
            kwh: number;
            /** Rate Cents Per Kwh */
            rate_cents_per_kwh: number | null;
            /** Amount Cents */
            amount_cents: number | null;
            /**
             * Unpriced
             * @default false
             */
            unpriced: boolean;
        };
        /** Body_api_ai_apply_api_ai_apply_post */
        Body_api_ai_apply_api_ai_apply_post: {
            /** Inverter Id */
            inverter_id: number;
        };
        /** Body_api_ai_recommend_api_ai_recommend_post */
        Body_api_ai_recommend_api_ai_recommend_post: {
            /** Inverter Id */
            inverter_id?: number | null;
        };
        /** Body_api_inverters_api_inverters_post */
        Body_api_inverters_api_inverters_post: {
            /** Inverter Id */
            inverter_id?: number | null;
            /** Name */
            name: string;
            /** Model */
            model: string;
            /** Adapter Kind */
            adapter_kind: string;
            /**
             * Ip Address
             * @default
             */
            ip_address: string;
            /**
             * Subnet
             * @default
             */
            subnet: string;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Battery Feed In Limit Kw
             * @default 0
             */
            battery_feed_in_limit_kw: number;
            /**
             * Battery Reserve Percent
             * @default 20
             */
            battery_reserve_percent: number;
            /**
             * Export Limit Kw
             * @default 0
             */
            export_limit_kw: number;
            /**
             * Allow Grid Charge
             * @default false
             */
            allow_grid_charge: boolean;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** Body_api_plans_api_plans_post */
        Body_api_plans_api_plans_post: {
            /** Plan Id */
            plan_id?: number | null;
            /** Provider Name */
            provider_name: string;
            /** Plan Name */
            plan_name: string;
            /** Billing Cycle */
            billing_cycle: string;
            /** Billing Start Day */
            billing_start_day: number;
            /** Billing Start Month */
            billing_start_month: number;
            /**
             * Daily Supply Charge
             * @default $0.00
             */
            daily_supply_charge: string;
            /**
             * Export Tier Kwh
             * @default 0
             */
            export_tier_kwh: number;
            /**
             * Export Tier Rate Cents Per Kwh
             * @default 0
             */
            export_tier_rate_cents_per_kwh: number;
            /**
             * Export Excess Rate Cents Per Kwh
             * @default 0
             */
            export_excess_rate_cents_per_kwh: number;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** Body_api_settings_api_settings_post */
        Body_api_settings_api_settings_post: {
            /** Theme */
            theme: string;
            /** Mode */
            mode: string;
            /** Site Name */
            site_name: string;
            /** Site Lat */
            site_lat: number;
            /** Site Lon */
            site_lon: number;
            /**
             * Site Timezone
             * @default Australia/Brisbane
             */
            site_timezone: string;
            /** Poll Interval Seconds */
            poll_interval_seconds: number;
            /**
             * Active Plan Id
             * @default
             */
            active_plan_id: string;
        };
        /** Body_api_tou_api_tou__plan_id__post */
        Body_api_tou_api_tou__plan_id__post: {
            /** Payload */
            payload: string;
            /**
             * Daily Supply Charge
             * @default $0.00
             */
            daily_supply_charge: string;
            /**
             * Export Tier Kwh
             * @default 0
             */
            export_tier_kwh: number;
            /**
             * Export Tier Rate Cents Per Kwh
             * @default 0
             */
            export_tier_rate_cents_per_kwh: number;
            /**
             * Export Excess Rate Cents Per Kwh
             * @default 0
             */
            export_excess_rate_cents_per_kwh: number;
        };
        /** ChartPointResponse */
        ChartPointResponse: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Amount Cents */
            amount_cents: number;
        };
        /** ChartResponse */
        ChartResponse: {
            /** Points */
            points: components["schemas"]["ChartPointResponse"][];
        };
        /** CloseDayResponse */
        CloseDayResponse: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Solar Kwh */
            solar_kwh: number;
            /** Grid Import Kwh */
            grid_import_kwh: number;
            /** Grid Export Kwh */
            grid_export_kwh: number;
        };
        /** DailyEnergyTotalsResponse */
        DailyEnergyTotalsResponse: {
            /** Solar Total Kwh */
            solar_total_kwh: number;
            /** Load Total Kwh */
            load_total_kwh: number;
            /** Grid Import Total Kwh */
            grid_import_total_kwh: number;
            /** Grid Export Total Kwh */
            grid_export_total_kwh: number;
            /** Battery Charge Total Kwh */
            battery_charge_total_kwh: number;
            /** Battery Discharge Total Kwh */
            battery_discharge_total_kwh: number;
        };
        /** DashboardStateResponse */
        DashboardStateResponse: {
            settings: components["schemas"]["AppSettings"];
            /** Inverters */
            inverters: components["schemas"]["InverterResponse"][];
            /** Power Plans */
            power_plans: components["schemas"]["PowerPlanResponse"][];
            live: components["schemas"]["LivePowerResponse"] | null;
            totals: components["schemas"]["DailyEnergyTotalsResponse"] | null;
            /** Live Observed At */
            live_observed_at: string | null;
            /** All Reachable */
            all_reachable: boolean;
            bill: components["schemas"]["BillSummaryResponse"];
            /**
             * Theme
             * @enum {string}
             */
            theme: "classic-light" | "classic-dark" | "deep-ocean" | "ember-core";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InverterResponse */
        InverterResponse: {
            /** Id */
            id?: number | null;
            /** Name */
            name: string;
            /**
             * Model
             * @default SigenStor EC 20.0 TP AU
             */
            model: string;
            /**
             * Adapter Kind
             * @default sigenstor_ec_20_0_tp_au
             * @constant
             */
            adapter_kind: "sigenstor_ec_20_0_tp_au";
            /**
             * Ip Address
             * @default
             */
            ip_address: string;
            /**
             * Subnet
             * @default
             */
            subnet: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Battery Feed In Limit Kw
             * @default 0
             */
            battery_feed_in_limit_kw: number;
            /**
             * Battery Reserve Percent
             * @default 20
             */
            battery_reserve_percent: number;
            /**
             * Export Limit Kw
             * @default 0
             */
            export_limit_kw: number;
            /**
             * Allow Grid Charge
             * @default false
             */
            allow_grid_charge: boolean;
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Reachable
             * @default false
             */
            reachable: boolean;
        };
        /** LivePowerResponse */
        LivePowerResponse: {
            /** Solar Kw */
            solar_kw: number;
            /** Load Kw */
            load_kw: number;
            /** Grid Import Kw */
            grid_import_kw: number;
            /** Grid Export Kw */
            grid_export_kw: number;
            /** Battery Charge Kw */
            battery_charge_kw: number;
            /** Battery Discharge Kw */
            battery_discharge_kw: number;
        };
        /** MutationErrorDetail */
        MutationErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** MutationErrorResponse */
        MutationErrorResponse: {
            /**
             * Ok
             * @default false
             * @constant
             */
            ok: false;
            error: components["schemas"]["MutationErrorDetail"];
        };
        /** MutationSuccessResponse */
        MutationSuccessResponse: {
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
            /** Redirect To */
            redirect_to: string;
            /** Resource Id */
            resource_id?: number | null;
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
        };
        /** PowerPlanResponse */
        PowerPlanResponse: {
            /** Id */
            id: number;
            /** Provider Name */
            provider_name: string;
            /** Plan Name */
            plan_name: string;
            /**
             * Billing Cycle
             * @default monthly
             * @enum {string}
             */
            billing_cycle: "monthly" | "quarterly";
            /**
             * Billing Start Day
             * @default 1
             */
            billing_start_day: number;
            /**
             * Billing Start Month
             * @default 1
             */
            billing_start_month: number;
            /**
             * Daily Supply Charge Cents
             * @default 0
             */
            daily_supply_charge_cents: number;
            /**
             * Export Tier Kwh
             * @default 0
             */
            export_tier_kwh: number;
            /**
             * Export Tier Rate Cents Per Kwh
             * @default 0
             */
            export_tier_rate_cents_per_kwh: number;
            /**
             * Export Excess Rate Cents Per Kwh
             * @default 0
             */
            export_excess_rate_cents_per_kwh: number;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** TouPeriodResponse */
        TouPeriodResponse: {
            /** Id */
            id: number;
            /** Plan Id */
            plan_id: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "import" | "export";
            /** Label */
            label: string;
            /** Start Minute */
            start_minute: number;
            /** End Minute */
            end_minute: number;
            /** Rate Cents Per Kwh */
            rate_cents_per_kwh: number;
        };
        /** TouPeriodsResponse */
        TouPeriodsResponse: {
            /** Plan Id */
            plan_id: number;
            /** Periods */
            periods: components["schemas"]["TouPeriodResponse"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeatherRecommendationResponse */
        WeatherRecommendationResponse: {
            /** Weather */
            weather: {
                [key: string]: unknown;
            };
            /** Recommendation */
            recommendation: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dashboard__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    settings_page_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    inverters_page_inverters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    plans_page_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    billing_page_billing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    api_state_api_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStateResponse"];
                };
            };
        };
    };
    api_chart_api_chart_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_bill_api_bill_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillSummaryResponse"];
                };
            };
        };
    };
    api_close_day_api_close_day_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloseDayResponse"];
                };
            };
        };
    };
    api_tou_read_api_plans__plan_id__tou_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TouPeriodsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_settings_api_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_api_settings_api_settings_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationSuccessResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
        };
    };
    api_inverters_api_inverters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_api_inverters_api_inverters_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationSuccessResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
        };
    };
    api_plans_api_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_api_plans_api_plans_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationSuccessResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
        };
    };
    api_tou_api_tou__plan_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_api_tou_api_tou__plan_id__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationSuccessResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
        };
    };
    api_poll_now_api_poll_now_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationSuccessResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
        };
    };
    api_ai_recommend_api_ai_recommend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_api_ai_recommend_api_ai_recommend_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherRecommendationResponse"] | components["schemas"]["MutationSuccessResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
        };
    };
    api_ai_apply_api_ai_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_api_ai_apply_api_ai_apply_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationSuccessResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationErrorResponse"];
                };
            };
        };
    };
}
